[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
event_protocol_sc = "6vG8Nz6smWS5BDdCowUdaEWAC4F8RAVEmGDD3j5ittMk"
[programs.devnet]
event_protocol_sc = "6vG8Nz6smWS5BDdCowUdaEWAC4F8RAVEmGDD3j5ittMk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lainhathoang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
