[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
event_protocol = "Fz24nmvrheUJJXbSwbMkP6FpMFFxbjuDqV99AZLWmASf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
